
// Some hard-coded constant

export const reducerCases = {
        SET_USER_INFO : "SET_USER_INFO",
        SET_NEW_USER : "SET_NEW_USER",
        SET_ALL_CONTACTS_PAGE : "SET_ALL_CONTACTS_PAGE",   // --> its for loading all contacts
        CHANGE_CURRENT_CHAT_USER :"CHANGE_CURRENT_CHAT_USER ",
        SET_MESSAGES: "SET_MESSAGES",
        UPDATE_UNREAD_MESSAGES : "UPDATE_UNREAD_MESSAGES",

        SET_SOCKET : "SET_SOCKET",
        ADD_MESSAGE: "ADD_MESSAGE",
        SET_CURRENTLY_PLAYING_AUDIO :"SET_CURRENTLY_PLAYING_AUDIO",
        SET_MEASSAGE_SEARCH : "SET_MEASSAGE_SEARCH",
        SET_USER_CONTACTS : "SET_USER_CONTACTS",
        SET_ONLINE_USERS: "SET_ONLINE_USERS",

        SET_CONTACT_SEARCH : "SET_CONTACT_SEARCH",

        SET_VOICE_CALL : "SET_VOICE_CALL",
        SET_VIDEO_CALL : "SET_VIDEO_CALL",
        END_CALL: "END_CALL",
        SET_INCOMING_VOICE_CALL : "SET_INCOMING_VOICE_CALL",
        SET_INCOMING_VIDEO_CALL : "SET_INCOMING_VIDEO_CALL",

        SET_EXIT_CHAT : "SET_EXIT_CHAT",

        META_AI__API : "META_AI_API",
        SET_LOADING : "SET_LOADING",

        SET_CREATE_GROUP : "SET_CREATE_GROUP",

        EDIT_PROFILE_DETAILS : "EDIT_PROFILE_DETAILS",
        EDIT_PROFILE_IMAGE : "EDIT_PROFILE_IMAGE",

        MARK_MESSAGE_AS_READ : "MARK_MESSAGE_AS_READ",
        SET_IS_SHOW_PROFILE_UPDATE_MODAL : "SET_IS_SHOW_PROFILE_UPDATE_MODAL",

        SET_RECENTLY_UPDATES_STATUS : "SET_RECENTLY_UPDATES_STATUS",
        SET_MY_STATUS : "SET_MY_STATUS",
        SET_VIEWED_UPDATE_STATUS : "SET_VIEWED_UPDATE_STATUS",
}